version: "3.7"

services:
    app_proxy:
        environment:
            APP_HOST: miniharri-store-stump_server_1
            APP_PORT: 10801

    server:
        image: aaronleopold/stump:latest
        init: true
        volumes:
            - ${APP_DATA_DIR}/data/config:/config
            - ${APP_DATA_DIR}/data:/data